config:
  zone: d3adb5.ca
  dynamicRecords:
    - dyn.d3adb5.ca
  protocol: cloudflare
  credentials:
    secretName: ddclient-credentials
    passwordKey: password

image:
  repository: ghcr.io/d3adb5/ddclient
  tag: 4.0.0
